### ISSUE TITLE
What IDE did u use?

### ISSUE THREAD

**Issue by Lovnx** [ConSol/java9-modules-maven-junit-example#3]

**Comment by jklingen** [comment]
Please note that the current state is a few months old - I'll merge a PR for an updated version soon (see #2).

By the time I put this together I have been using an _early preview version_ of IntelliJ IDEA Ultimate 2017, which still had mediocre Java9 support. The latest version does a great job with Java 9 😃

**Comment by Lovnx** [comment]
OK, Thanks, I downloaded the latest version of IntelliJ IDEA and it runs well. Maybe u can post what new features of Java9 u used on the README. I guess.
